# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fd3ebc0a805eeb7beb32ee98c9982f6dcbe5399197126a36b654c5290e4fb50644abc2423f5fa65cc20c29fe24d1b29600a088a5b7aafcb6ca5ca5688a9d3777

test:
  secret_key_base: 1d9ca6933c4b62f2ea976e86bd32d501034970f3b8fb11d84bafa4bcf403d16f9ef2810aa2e8ece84e37b0c311f45cdda1bc2a4f1d53b7d16a3e959aa180f19a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
